### ISSUE TITLE
Error creating records in Node environment

### ISSUE THREAD

**Issue by B-Reif** [tommikaikkonen/redux-orm#194]
I'm trying to test some of the functionality of my models. When the test suite tries to do `Model.create({})`, an error occurs:
```
FAIL  src/restructurers/AnswerContent.test.js  ● normalizes an answer content
  TypeError: Class constructor AnswerContent cannot be invoked without 'new'      
    at new SessionBoundModel (node_modules/redux-orm/lib/Session.js:69:87)      
    at Function.create (node_modules/redux-orm/lib/Model.js:339:24)      
    at Function.create (node_modules/redux-orm-proptypes/lib/index.js:120:95)      
    at Object.<anonymous>.test (src/restructurers/AnswerContent.test.js:28:38)
    at new Promise (<anonymous>)
    at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
    at <anonymous>
```

The transpiled code that's erroring out looks like:
```js
var sessionBoundModel = function (_modelClass) {
  (0, _inherits3.default)(SessionBoundModel, _modelClass);

  function SessionBoundModel() {
    (0, _classCallCheck3.default)(this, SessionBoundModel);
    return (0, _possibleConstructorReturn3.default)(this, _modelClass.apply(this, arguments));
  }
  return SessionBoundModel;
}(modelClass);
```

In the source:
```js
this.sessionBoundModels = this.models.map((modelClass) => {
  const sessionBoundModel = class SessionBoundModel extends modelClass {};
  // ...
});
```

I'm running this in the terminal with Jest.

**Comment by markerikson** [comment]
Yeah, I experienced that at one point, and my solution was to avoid mixing transpiled and non-transpiled use of `class`.  Since I was already using `babel-preset-env` and _not_ transpiling `class` in my app code, I updated Webpack to resolve `redux-orm` to `"node_modules/redux-orm/src"`.

**Comment by B-Reif** [comment]
That's a good hack! I guess that means I finally have to `eject`.

This still seems kinda crummy though.

**Comment by markerikson** [comment]
No need to eject - you should be able to use https://github.com/timarney/react-app-rewired to override that bit of the config.

**Comment by B-Reif** [comment]
So now I'm running into a mismatch where my app classes _are_ transpiled, but `redux-orm/src` is (obviously) not. But in the test environment, my app's classes are _not_ transpiled, but redux-orm _is_? I'm not sure what my recourse would be here.

**Comment by markerikson** [comment]
I think your best bet is to ensure that classes aren't getting transpiled on either side.

**Comment by B-Reif** [comment]
So to do this, I'll have to setup Babel with the "env" preset. As far as I can tell, `react-app-rewired` just has `injectBabelPlugin`, but no ability to inject an entire preset. Should I just manually list the plugins I need? Or is there a way to inject a preset?

**Comment by B-Reif** [comment]
It looks like the CRA config actually uses env already?
https://github.com/facebook/create-react-app/blob/v1.1.1/packages/babel-preset-react-app/index.js

**Comment by markerikson** [comment]
Right, it does, so you'd need to change its target browsers to those that support ES6 classes already.

(This assumes your app's deployment environment doesn't care about pre-ES6 browsers.)

**Comment by Chris-Congenica** [comment]
Hey,

I'm running into a similar issue, I understand what you guys are talking about but I'm unsure how to change my config to get this working. Could you post an example?

Cheers.

**Comment by Aerendir** [comment]
Yes, I have the same error, too and I'm practically completely new to React, Redux, redux-orm and all other things... I'm learning (thank you @markerikson for your fantastic mini-meck tutorial: it's the best I've ever found on the entire Internet!!!).

So, question: how to configure WebPack to correctly compile `redux-orm`? I'm not using `create-react-app`, so I'm free to make all the editings required... I only need to be put on the right path...
