### ISSUE TITLE
Getting error "Class constructor Record cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by a-s-o** [tommikaikkonen/redux-orm#53]
Hello,

Just trying out redux orm and I am getting the following error after a basic Model.create

```
TypeError: Class constructor Record cannot be invoked without 'new'

  at new SessionBoundModel (../node_modules/redux-orm/lib/Session.js:77:124) <-- redux-orm internal
  at Function.create (../node_modules/redux-orm/lib/Model.js:663:28) <-- session.Record.create
  at Object.RECORD_ADDED (state/orm/models.js:39:16) <-- event inside Record.reducer
  at Function.reducerForRecord [as reducer] (state/orm/models.js:63:28)  <-- Record.reducer
```

Here is my model:

``` javascript
// My domain is a database; record is a row which has many fields; fields can
// be of many types but they only exist in the context of a record; if a record is deleted
// fields must also be deleted.

export class Record extends Model {}

Record.modelName = 'Record'

Record.fields = {
  fields: many('Field')
}

// Please note that makeReducer() isn't doing anything fancy; just matches event.type
// to each specific function and passes session as third argument instead of the model class   
// Error is same if reducer is written with a switch statement
Record.reducer = makeReducer(Record, {

  [events.RECORD_ADDED] (state, event, session) {
    session.Record.create({ id: event.id })    // <--- this is where the error occurs
  },

  [events.FIELD_ADDED] (state, event, session) {
    session.Record.withId(event.record).fields.add(event.id)
  },

  [events.FIELD_REMOVED] (state, event, session) {
    const field = session.Field.withId(event.id)
    const record = session.Record.withId(field.record)

    record.fields.remove(event.id)
  }

})
```

This also happens with other models (for instance the `Field` model referenced above). I also tried installing redux-orm v0.8.3 version to see if this was a regression.

Since all the examples show the `create` static method being called to initialize models,  I have not tried attempted to call new directly.

Hope that is clear, let me know if you need more info.

Thanks for the package; I hope it will be useful.

**Comment by carlo** [comment]
@a-s-o, I have the same problem w/ 0.9.0-rc3 — did you ever find a solution?

**Comment by carlo** [comment]
Update: I found a working solution for my own case (i.e. a non-transpiled Electron app). 

Basically, redux-orm's transpiled ES5 code clashes with vanilla ES6 code here — ES6 classes can't be invoked without `new`, but that's what the library is trying to do. So using a `Proxy` object is a good workaround. (See the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).)

Here's a helper function that'll overwrite `klass.apply()` so when it is called, it'll correctly invoke the class:

```es6
function proxyClassForORM(klass) {
  return new Proxy(klass, {
    apply(target, thisArg, rest) {
      return new target(...rest);
    },
  });
}
```

In your `models.js`, wrap your original class objects before registering them:

```es6
// Before
const orm = new ORM();
orm.register(Record);

// After
const orm = new ORM();
orm.register(
  proxyClassForORM(Record)
);
```

Works for me, YMMV.  @tommikaikkonen, this might be something for the docs (if you approve of the workaround and explanation).

**Comment by markerikson** [comment]
Ouch.  Seems kinda nasty, but nice detective work, and thanks for posting the info.

**Comment by chanan** [comment]
This somewhat worked for me, but moved the problem somewhere else.

First of all, I didnt seem to run into this problem in my regular code. I only had this occur when writing a test. Once I added the fix above the Model.create() did work but then I go this calling the reducer of the model:

```
TypeError: Cannot read property 'applyUpdate' of undefined

      at Form.update (node_modules\redux-orm\lib\Model.js:493:26)
      at Function.reducer (src\models\index.js:43:48)
```

**Comment by nealoke** [comment]
@chanan any update on this issue?

**Comment by levity** [comment]
@chanan my team ran into that issue as well -- what we ended up doing was making sure we only applied @carlo's workaround during tests:

```js
function proxyClassForORM(klass) {
  if (!navigator.userAgent.includes('Node.js')) return klass
  return new Proxy(klass, {
    apply(target, thisArg, rest) {
      return new target(...rest);
    },
  });
}
```

If you have a server-side environment that uses ES5 code (e.g. for server-side rendering), you'll have to add an additional check for that.

**Comment by levity** [comment]
@chanan maybe the workaround I came up with (linked above) will work for you.

**Comment by nealoke** [comment]
@levity I've found the cause (which was not this), see #107

**Comment by levity** [comment]
@nealoke yes, I noticed you had a different issue which caused the same error message.

**Comment by markerikson** [comment]
Huh.  So, I actually ran into this myself recently, but didn't think to search for it exactly.  I was able to resolve this by tweaking my Webpack config to have it pull in the `redux--orm/src` folder so that I used the uncompiled source myself, rather than the precompiled source.  In my Webpack config, I added:

```js
    alias : {
        "redux-orm" : "redux-orm/src"
    }

**Comment by NathanBWaters** [comment]
Definitely reopened because it sounds like we should look into this.  Thanks @markerikson for the heads up!

**Comment by markerikson** [comment]
Yeah, @carlo 's analysis is correct - it's a clash between using real ES6 classes in one place, and transpiled classes in another.  This is likely to happen if you move to something like `babel-preset-env` for your application's code and target only newer browsers.  Your app's code will contain real classes, while `node_modules/redux-orm/lib` will contain transpiled classes.

**Comment by timrichd** [comment]
hmm not working for me with `create-react-app` skeleton

**Comment by timrichd** [comment]
Any solutions for this? Is this going to be in the next release?

**Comment by levity** [comment]
@timrichd if you need a solution now, check out the fork that I linked above, which adds a `Model.createClass` workaround.

**Comment by JulioC** [comment]
This issue happens on my react-native@0.46.4 app

**Comment by mpontus** [comment]
To give higher perspective, this issue prevents redux-orm code from being tested in create-react-app environment (which uses jest with [this](https://github.com/facebookincubator/create-react-app/blob/c00358376b50e44313671384c64faf420e8d0c0a/packages/babel-preset-react-app/index.js#L71) babel configuration).

I would also like to link relevant discussion from babel issues: https://github.com/babel/babel/issues/4269. As far as I can tell from the resolution, it is not possible for transpiled classes to extend from native classes.

With that in mind, I think we should discuss a viable long term solution. Perhaps someone with more knowledge about the codebase than myself can weight in with a conceptual outline of the required changes?

**Comment by janoist1** [comment]
@carlo Thanks for sharing your solution!

**Comment by Aerendir** [comment]
Ok, thanks to the @markerikson 's suggestion, I solved in a first place my issue.

I added this:

    alias : {
        "redux-orm" : "redux-orm/src"
    }

This solved the error for me.

But continuing the development, I updated to `@babel/preset-env` and this broke again with the same error.

Removing the line solved the issue again.

I don't know what happened nor why it happened, but maybe this clarification can be of help for others.

If someone with more experience knows why I had those issue I'll be glad to hear!

**Comment by frederic-bonjour** [comment]
Same problem here, when running _redux-orm_ in a Node.js app (with Redux used server-side).
Any chance to get that fixed quickly?
_redux-orm_ seems very interesting, and I'd really want to use it...

**Comment by sheppard** [comment]
I tried adding "module": "src/index.js" to package.json (see #192).  This fixed the issue for me with the latest create-react-app and babel.  Does the fix work for anyone else?

**Comment by Amareis** [comment]
It's brokes all for me. Webpack import es6 class from `module` field, then babel transpile my model classes to es5 and BOOM `Uncaught TypeError: Cannot call a class as a function` on every `new MyModel`

**Comment by haveyaseen** [comment]
@Amareis I think I have had a similar issue (it bit me personally with the object spread operator in `Session.js`). Could you try excluding the library from `babel-loader`'s excludes? No idea if this is actually a solution that we should be okay with, but it definitely worked for me.

**webpack.config.js**
```diff
-        exclude: /(node_modules|bower_components)/,
+        exclude: /(node_modules|bower_components)\/(?!redux-orm)/,
```

**Comment by Amareis** [comment]
Yeah, I try it and it's working, but then I ran into this spread operator issue also. Finally (after hours of painful debug) I just down redux-orm version to 0.9.3

**Comment by haveyaseen** [comment]
That is very unfortunate to hear so I have looked into it some more.
If it's just the spread operator causing the issue, then you can probably fix it by

1. requiring `babel-preset-stage-3` using
`npm install babel-preset-stage-3` or
`yarn add babel-preset-stage-3` and then
2. adding `'stage-3'` to `babel-loader`'s `presets` array in `webpack.config.js`.

And luckily there is also an alternative to revert to the old behavior! You can apparently ignore the new `pkg.module` key and use the transpiled files in `lib/` instead by adding a [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) key to your `webpack.config.js` like this:
```javascript
module.exports = {
 ...
  resolve: {
    // by default this includes 'module' which is what we want to avoid
    // see the Webpack docs if you really need 'browser'
    mainFields: ['browser', 'main'],
  },
};
```
If you choose the latter option, make sure to undo the addition removing `redux-orm` from `babel-loader`'s excludes.

Hope this helps you so you don't have to miss out on our new performance improvements!

**Comment by Amareis** [comment]
Heh, one does not simply add preset-stage-2 to babelrc because babelrc from redux-orm take precedence (also, I already have stage-0). But `mainFields` thing did the trick, thank you mate!

**Comment by haveyaseen** [comment]
Requiring our users to transpile library code using Babel is not a good thing:

- [`pkg.module` is not intended for untranspiled code](https://github.com/rollup/rollup/wiki/pkg.module). It's not even standardized.
- We require a set of plugins in `.babelrc` which breaks the build for everyone not using them.
- When `.babelrc` will Babel v7 this will break the build for everyone not using Babel v7.

We should transpile to the latest finalized ES version and ship this in a different subfolder (`"module": "es/index.js"`), [just like Redux does.](https://github.com/reduxjs/redux/blob/master/package.json)

**Comment by haveyaseen** [comment]
Alright, **v0.10.2** should not require transpilation for ES2017-compatible environments anymore. @Amareis @markerikson @sheppard Would you mind trying the new release?
The `resolve.mainFields` field can be removed now for anyone using `babel-preset-env`.

**Comment by Amareis** [comment]
@haveyaseen yeah, it's working now without `mainFields`, big thanks!

**Comment by ojab** [comment]
Still reproducible here with babel@6 & redux-orm@0.10.2:
```json
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "last 2 Chrome versions",
            "last 2 Firefox versions",
            "last 1 Safari version"
          ]
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
```

**Comment by markerikson** [comment]
Clearly this is still a pain point.

Is there an alternative way we can implement the overall behavior of Redux-ORM and sessions, without relying on this dynamic subclassing approach?

**Comment by plandem** [comment]
@markerikson that's thing that I dislike most. But had not good idea in the past :(

**Comment by markerikson** [comment]
Architecturally, I think the issue is that `Model` is full of static methods that reference a static `this.session` field.  

I guess there's a couple aspects that need to be solved:

- What use cases are there for having multiple Sessions active at once?
- Assuming we still want to allow multiple simultaneous Sessions, is there a way to have a static method / class definition determine what the correct Session instance is as it's running?

There's gotta be something that can be done with, I dunno, unique IDs and lookup tables somehow.

**Comment by haveyaseen** [comment]
It would be great if we could solve this on an architectural basis as ES classes are downright backwards-incompatible. However, for now I think the following may suffice (transpiling and testing with ES6 works):
```javascript
this.sessionBoundModels = this.models.map((modelClass) => {
    function SessionBoundModel() {
        return Reflect.construct(modelClass, arguments, SessionBoundModel);
    }
    Reflect.setPrototypeOf(SessionBoundModel.prototype, modelClass.prototype);
    Reflect.setPrototypeOf(SessionBoundModel, modelClass);

    Object.defineProperty(this, modelClass.modelName, {
        get: () => SessionBoundModel,
    });

    SessionBoundModel.connect(this);
    return SessionBoundModel;
});
```
Source: https://esdiscuss.org/topic/extending-an-es6-class-using-es5-syntax#content-2

**Comment by haveyaseen** [comment]
@plandem Did you have any idea yet on how to solve this architecturally? I have to say that I doubt there is any clean way of solving this without performance degradations.

@markerikson We do need concurrent sessions for both reducers and selectors to work independently from the user's code. And for users to be able to perform (potentially asynchronous) fast but non-memoizable model creation/updates using mutable sessions.

https://github.com/tommikaikkonen/redux-orm/blob/dd89014a2ef451867823b0b106a1bd0e820adaa5/src/redux.js#L34

https://github.com/tommikaikkonen/redux-orm/blob/00f7d709385685f89bceba1dd52c2a94e037bec7/src/memoize.js#L153

I have tried different things, even the other suggestion in my previously linked source where you define the constructor using a `_constructor` method which is called by the class constructor and overriding `Model.call` and `Model.apply`. This works but its just as bad for performance.

Another potential solution would be to differentiate between transpiled classes and actual classes which could work using a try-catch block around a `modelClass()` call and parsing the output to see if it was made by the JS engine or by the Babel code. Or something like [`is-class`](https://github.com/miguelmota/is-class/blob/master/is-class.js). However I failed to produce a significant difference between outputs of `Function.prototype.toString.call(modelClass)` `Function.prototype.toString.call(Object.getPrototypeOf(modelClass))`.

So all of this is extremely hacky. Only using functions and hoisting statics could work to some extent but it's not really clean, will probably lead to other bugs and has to be maintained.

Maybe we should just make this a won't fix and require users to use the ES6+ module if they want to use the *ES6 feature* of classes. #116 could be a way to satisfy ES5 users similar to `create-react-class`.

**Comment by plandem** [comment]
no working idea yet, let’s leave this issue open to remember “why”.

**Comment by Adwelean** [comment]
Anything new, a workaround solution?

**Comment by haveyaseen** [comment]
@Adwelean This issue should have been fixed with #213 (since v0.12.0). The fix just isn't highly performant.
